apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quicksilver666-com-tls
spec:
  secretName: quicksilver-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: quicksilver666.com
  dnsNames:
    - quicksilver666.com
    - www.quicksilver666.com